# Generated by Django 4.1.5 on 2023-01-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="driver_number",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
