# Generated by Django 4.1.5 on 2023-02-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_driver_driver_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=240),
        ),
    ]
